### ISSUE TITLE
Errors prevented startup/ng-script-compiler

### ISSUE THREAD

**Issue by jeremy-seipelt** [pbastowski/angular-meteor-babel#31]
When using $meteor run

I get the following error-message:
 
```
While processing files with pbastowski:angular-babel (for target web.browser):
packages/compileNGScript/plugin/ng-script-compiler.js:97:1: Cannot read property 'line' of undefined
  at processFile (packages/compileNGScript/plugin/ng-script-compiler.js:97:1)
  at Array.forEach (native)
  at Object.processFiles (packages/compileNGScript/plugin/ng-script-compiler.js:39:1)
```

Here is the complete Startup log:

```
=> Started proxy.                             
=> Started MongoDB.                           
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/angular/angular-animate.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/angular/angular.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/angular/angular.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/angular-ui/angular-ui-router.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/blob-stream.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/ionic-angular.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/ionic-angular.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/ionic.bundle.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/ionic.bundle.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/ionic.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/ionic/js/ionic.min.js" as it exceeds the max of "100KB".
{ [TypeError: /client/scripts/lib/ionic/js/pdfkit.js: name.toLowerCase is not a function] _babel: true }
=> Errors prevented startup:                  
   
   While processing files with pbastowski:angular-babel (for target web.browser):
   packages/compileNGScript/plugin/ng-script-compiler.js:97:1: Cannot read property 'line' of undefined
   at processFile (packages/compileNGScript/plugin/ng-script-compiler.js:97:1)
   at Array.forEach (native)
   at Object.processFiles (packages/compileNGScript/plugin/ng-script-compiler.js:39:1)
   
   
=> Your application has errors. Waiting for file change.
```

I would appreciate if there is a way for finding the source of this error. I cant even find  ng-script-compiler.js in my Project folder to look what happens at line 97.

here is my meteor list:

```
angular                1.3.11  Everything you need to use AngularJS in your Meteor app
angular-templates      1.0.9  Compile angular templates into the template cache
autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
dab0mb:ionic-assets    1.3.5  Ionic assets pack
es5-shim               4.6.15  Shims and polyfills to improve ECMAScript 5 support
insecure               1.0.7  (For prototyping only) Allow all database writes from the client
jquery                 1.11.10  Manipulate the DOM using CSS selectors
meteor-base            1.0.4  Packages that every Meteor app needs
mobile-experience      1.0.4  Packages for a great mobile user experience
mongo                  1.1.14  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.11  Reactive variable
shell-server           0.2.1  Server-side component of the `meteor shell` command.
standard-minifier-css  1.3.2  Standard css minifier used with Meteor apps by default.
standard-minifier-js   1.2.1  Standard javascript minifiers used with Meteor apps by default.
tracker                1.1.1  Dependency tracker to allow reactive callbacks
```

and my npm list:

```
├── angular@1.5.8 
├── angular-animate@1.5.8 
├─┬ angular-meteor@1.3.11 
│ ├─┬ jsondiffpatch@0.1.43 
│ │ └─┬ chalk@0.5.1 
│ │   ├── ansi-styles@1.1.0 
│ │   ├── escape-string-regexp@1.0.5 
│ │   ├─┬ has-ansi@0.1.0 
│ │   │ └── ansi-regex@0.2.1 
│ │   ├── strip-ansi@0.3.0 
│ │   └── supports-color@0.2.0 
│ └── underscore@1.8.3 
├── angular-sanitize@1.5.8 
├── angular-ui-router@0.3.1 
├─┬ ionic-scripts@1.3.5 
│ └── ionic-sdk-unofficial@1.3.1 
└─┬ meteor-node-stubs@0.2.3 
  ├── assert@1.3.0 
  ├─┬ browserify-zlib@0.1.4 
  │ └── pako@0.2.8 
  ├─┬ buffer@4.5.1 
  │ ├── base64-js@1.1.2 
  │ ├── ieee754@1.1.6 
  │ └── isarray@1.0.0 
  ├─┬ console-browserify@1.1.0 
  │ └── date-now@0.1.4 
  ├── constants-browserify@1.0.0 
  ├─┬ crypto-browserify@3.11.0 
  │ ├─┬ browserify-cipher@1.0.0 
  │ │ ├─┬ browserify-aes@1.0.6 
  │ │ │ ├── buffer-xor@1.0.3 
  │ │ │ └── cipher-base@1.0.2 
  │ │ ├─┬ browserify-des@1.0.0 
  │ │ │ ├── cipher-base@1.0.2 
  │ │ │ └─┬ des.js@1.0.0 
  │ │ │   └── minimalistic-assert@1.0.0 
  │ │ └── evp_bytestokey@1.0.0 
  │ ├─┬ browserify-sign@4.0.0 
  │ │ ├── bn.js@4.11.1 
  │ │ ├── browserify-rsa@4.0.1 
  │ │ ├─┬ elliptic@6.2.3 
  │ │ │ ├── brorand@1.0.5 
  │ │ │ └── hash.js@1.0.3 
  │ │ └─┬ parse-asn1@5.0.0 
  │ │   ├─┬ asn1.js@4.5.2 
  │ │   │ └── minimalistic-assert@1.0.0 
  │ │   ├─┬ browserify-aes@1.0.6 
  │ │   │ ├── buffer-xor@1.0.3 
  │ │   │ └── cipher-base@1.0.2 
  │ │   └── evp_bytestokey@1.0.0 
  │ ├─┬ create-ecdh@4.0.0 
  │ │ ├── bn.js@4.11.1 
  │ │ └─┬ elliptic@6.2.3 
  │ │   ├── brorand@1.0.5 
  │ │   └── hash.js@1.0.3 
  │ ├─┬ create-hash@1.1.2 
  │ │ ├── cipher-base@1.0.2 
  │ │ ├── ripemd160@1.0.1 
  │ │ └── sha.js@2.4.5 
  │ ├── create-hmac@1.1.4 
  │ ├─┬ diffie-hellman@5.0.2 
  │ │ ├── bn.js@4.11.1 
  │ │ └─┬ miller-rabin@4.0.0 
  │ │   └── brorand@1.0.5 
  │ ├── inherits@2.0.1 
  │ ├── pbkdf2@3.0.4 
  │ ├─┬ public-encrypt@4.0.0 
  │ │ ├── bn.js@4.11.1 
  │ │ ├── browserify-rsa@4.0.1 
  │ │ └─┬ parse-asn1@5.0.0 
  │ │   ├─┬ asn1.js@4.5.2 
  │ │   │ └── minimalistic-assert@1.0.0 
  │ │   ├─┬ browserify-aes@1.0.6 
  │ │   │ ├── buffer-xor@1.0.3 
  │ │   │ └── cipher-base@1.0.2 
  │ │   └── evp_bytestokey@1.0.0 
  │ └── randombytes@2.0.3 
  ├── domain-browser@1.1.7 
  ├── events@1.1.0 
  ├─┬ http-browserify@1.7.0 
  │ ├── Base64@0.2.1 
  │ └── inherits@2.0.1 
  ├── https-browserify@0.0.1 
  ├── os-browserify@0.2.1 
  ├── path-browserify@0.0.0 
  ├── process@0.11.2 
  ├── punycode@1.4.1 
  ├── querystring-es3@0.2.1 
  ├─┬ readable-stream@2.0.6 
  │ ├── core-util-is@1.0.2 
  │ ├── inherits@2.0.1 
  │ ├── isarray@1.0.0 
  │ ├── process-nextick-args@1.0.6 
  │ └── util-deprecate@1.0.2 
  ├─┬ stream-browserify@2.0.1 
  │ └── inherits@2.0.1 
  ├── string_decoder@0.10.31 
  ├── timers-browserify@1.4.2 
  ├── tty-browserify@0.0.0 
  ├─┬ url@0.11.0 
  │ ├── punycode@1.3.2 
  │ └── querystring@0.2.0 
  ├─┬ util@0.10.3 
  │ └── inherits@2.0.1 
  └─┬ vm-browserify@0.0.4 
    └── indexof@0.0.1 
```

Tell me if you need more Infos.

**Comment by pbastowski** [comment]
@jeremy-seipelt 
I have just published v1.3.7 with a bug fix. Please give it a try and let me know if it's better now.

Thanks.

**Comment by jeremy-seipelt** [comment]
I had to refractor my project to get some work done so i cant reproduce the issue anymore so you can close if you want

**Comment by pbastowski** [comment]
OK, thanks.
