### ISSUE TITLE
Unexpected character # while files with pbastowski:angular-babel

### ISSUE THREAD

**Issue by ananthavel** [pbastowski/angular-meteor-babel#34]
Hi Mate,
Im facing the below issue while running **$meter run android**  on my ubuntu machine. 

**Below is my console log :**
Started proxy.                             
=> A patch (Meteor 1.4.1.3) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While processing files with pbastowski:angular-babel (for target
   web.browser):
   packages/compileNGScript_plugin.js:117:23: error: couldn't process source
   due to parse error: 
   
   Unexpected character '#' (1:0)
   at processFile (packages/compileNGScript_plugin.js:117:23)
   at Array.forEach (native)
   at Object.processFiles (packages/compileNGScript_plugin.js:49:11)
   
   
   While processing files with pbastowski:angular-babel (for target
   web.cordova):
   packages/compileNGScript_plugin.js:117:23: error: couldn't process source
   due to parse error: 
   
   Unexpected character '#' (1:0)
   at processFile (packages/compileNGScript_plugin.js:117:23)
   at Array.forEach (native)
   at Object.processFiles (packages/compileNGScript_plugin.js:49:11)
   
   
   While processing files with pbastowski:angular-babel (for target
   os.linux.x86_64):
   packages/compileNGScript_plugin.js:117:23: error: couldn't process source
   due to parse error: 
   
   Unexpected character '#' (1:0)
   at processFile (packages/compileNGScript_plugin.js:117:23)
   at Array.forEach (native)
   at Object.processFiles (packages/compileNGScript_plugin.js:49:11)

**This is my packages.json file**

{
“name”: “XXX”,
“private”: true,
“scripts”: {
“start”: “meteor run”
},
“dependencies”: {
“angular”: “^1.6.0”,
“angular-material”: “^1.1.1”,
“angular-meteor”: “^1.3.11”,
“angular-touch”: “^1.6.2”,
“angular-ui-router”: “^0.3.2”,
“babel-runtime”: “^6.20.0”,
“bootstrap-ui-datetime-picker”: “^2.4.4”,
“meteor-node-stubs”: “^0.2.11”,
“tether”: “^1.4.0”
}
}

**Additional Info:**

.meteor/versions

.meteor/versions: line 1: accounts-base@1.2.11: command not found
.meteor/versions: line 2: accounts-password@1.3.0: command not found
.meteor/versions: line 3: accounts-ui@1.1.8: command not found
.meteor/versions: line 4: accounts-ui-unstyled@1.1.11: command not found
.meteor/versions: line 5: allow-deny@1.0.5: command not found
.meteor/versions: line 6: angular-templates@1.0.9: command not found
.meteor/versions: line 7: autoupdate@1.2.11: command not found
.meteor/versions: line 8: babel-compiler@6.9.1: command not found
.meteor/versions: line 9: babel-runtime@0.1.11: command not found
.meteor/versions: line 10: base64@1.0.9: command not found
.meteor/versions: line 11: binary-heap@1.0.9: command not found
.meteor/versions: line 12: blaze@2.1.8: command not found
.meteor/versions: line 13: blaze-html-templates@1.0.4: command not found
.meteor/versions: line 14: blaze-tools@1.0.9: command not found
.meteor/versions: line 15: boilerplate-generator@1.0.9: command not found
.meteor/versions: line 16: caching-compiler@1.0.6: command not found
.meteor/versions: line 17: caching-html-compiler@1.0.6: command not found
.meteor/versions: line 18: callback-hook@1.0.9: command not found
.meteor/versions: line 19: check@1.2.3: command not found
.meteor/versions: line 20: ddp@1.2.5: command not found
.meteor/versions: line 21: ddp-client@1.2.9: command not found
.meteor/versions: line 22: ddp-common@1.2.6: command not found
.meteor/versions: line 23: ddp-rate-limiter@1.0.5: command not found
.meteor/versions: line 24: ddp-server@1.2.10: command not found
.meteor/versions: line 25: deps@1.0.12: command not found
.meteor/versions: line 26: diff-sequence@1.0.6: command not found
.meteor/versions: line 27: dotansimha:accounts-ui-angular@0.0.4: command not found
.meteor/versions: line 28: ecmascript@0.5.8: command not found
.meteor/versions: line 29: ecmascript-runtime@0.3.14: command not found
.meteor/versions: line 30: ejson@1.0.12: command not found
.meteor/versions: line 31: email@1.1.17: command not found
.meteor/versions: line 32: es5-shim@4.6.14: command not found
.meteor/versions: line 33: fastclick@1.0.12: command not found
.meteor/versions: line 34: geojson-utils@1.0.9: command not found
.meteor/versions: line 35: hot-code-push@1.0.4: command not found
.meteor/versions: line 36: html-tools@1.0.10: command not found
.meteor/versions: line 37: htmljs@1.0.10: command not found
.meteor/versions: line 38: http@1.1.8: command not found
.meteor/versions: line 39: id-map@1.0.8: command not found
.meteor/versions: line 40: insecure@1.0.7: command not found
.meteor/versions: line 41: jquery@1.11.9: command not found
.meteor/versions: line 42: launch-screen@1.0.12: command not found
.meteor/versions: line 43: less@2.5.7: command not found
.meteor/versions: line 44: livedata@1.0.18: command not found
.meteor/versions: line 45: localstorage@1.0.11: command not found
.meteor/versions: line 46: logging@1.1.15: command not found
.meteor/versions: line 47: meteor@1.2.17: command not found
.meteor/versions: line 48: meteor-base@1.0.4: command not found
.meteor/versions: line 49: minifier-css@1.2.14: command not found
.meteor/versions: line 50: minifier-js@1.2.14: command not found
.meteor/versions: line 51: minimongo@1.0.17: command not found
.meteor/versions: line 52: mobile-experience@1.0.4: command not found
.meteor/versions: line 53: mobile-status-bar@1.0.12: command not found
.meteor/versions: line 54: modules@0.7.6: command not found
.meteor/versions: line 55: modules-runtime@0.7.6: command not found
.meteor/versions: line 56: mongo@1.1.12: command not found
.meteor/versions: line 57: mongo-id@1.0.5: command not found
.meteor/versions: line 58: npm-bcrypt@0.9.1: command not found
.meteor/versions: line 59: npm-mongo@1.5.48: command not found
.meteor/versions: line 60: observe-sequence@1.0.12: command not found
.meteor/versions: line 61: ordered-dict@1.0.8: command not found
.meteor/versions: line 62: pbastowski:angular-babel@1.3.7: command not found
.meteor/versions: line 63: promise@0.8.4: command not found
.meteor/versions: line 64: raix:eventemitter@0.1.3: command not found
.meteor/versions: line 65: raix:eventstate@0.0.4: command not found
.meteor/versions: line 66: raix:push@3.0.2: command not found
.meteor/versions: line 67: random@1.0.10: command not found
.meteor/versions: line 68: rate-limit@1.0.5: command not found
.meteor/versions: line 69: reactive-dict@1.1.8: command not found
.meteor/versions: line 70: reactive-var@1.0.10: command not found
.meteor/versions: line 71: reload@1.1.10: command not found
.meteor/versions: line 72: retry@1.0.8: command not found
.meteor/versions: line 73: routepolicy@1.0.11: command not found
.meteor/versions: line 74: service-configuration@1.0.10: command not found
.meteor/versions: line 75: session@1.1.6: command not found
.meteor/versions: line 76: sha@1.0.8: command not found
.meteor/versions: line 77: shell-server@0.2.1: command not found
.meteor/versions: line 78: spacebars@1.0.12: command not found
.meteor/versions: line 79: spacebars-compiler@1.0.12: command not found
.meteor/versions: line 80: srp@1.0.9: command not found
.meteor/versions: line 81: standard-minifier-css@1.2.0: command not found
.meteor/versions: line 82: standard-minifier-js@1.2.0: command not found
.meteor/versions: line 83: templating@1.1.14: command not found
.meteor/versions: line 84: templating-tools@1.0.4: command not found
.meteor/versions: line 85: tmeasday:check-npm-versions@0.1.1: command not found
.meteor/versions: line 86: tracker@1.1.0: command not found
.meteor/versions: line 87: twbs:bootstrap@3.3.6: command not found
.meteor/versions: line 88: ui@1.0.11: command not found
.meteor/versions: line 89: underscore@1.0.9: command not found
.meteor/versions: line 90: urigo:static-html-compiler@0.1.8: command not found
.meteor/versions: line 91: url@1.0.10: command not found
.meteor/versions: line 92: webapp@1.3.11: command not found
.meteor/versions: line 93: webapp-hashing@1.0.9: command not found

Can you direct me to fix this issue.

Regards,
Ananth S

**Comment by pbastowski** [comment]
Hi Ananth

I no longer support this package, which is why it breaks. 

Have you tried doing what was suggested by this other user: https://github.com/pbastowski/angular-meteor-babel/issues/33
