### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by ShimShamSam** [pbastowski/angular-meteor-babel#7]
```
   While loading plugin `compileNGScript` from package `pbastowski:angular-babel`:
   native: Unexpected token }
   at Object.parse (native)
   at getCustomConfig (packages/compileNGScript/plugin/ng-script-compiler.js:132:1)
   at Package (packages/compileNGScript/plugin/ng-script-compiler.js:25:1)
   at <runJavaScript-50>:155:4
   at <runJavaScript-50>:162:3
```

**Comment by pbastowski** [comment]
What is the exact contents of your .babelrc file?

**Comment by ShimShamSam** [comment]
Ah crap, I'm dumb. It was a trailing comma in my .babelrc file.
